### ISSUE TITLE
b2Vec2 won't free

### ISSUE THREAD

**Issue by SneakyFernando** [kripken/box2d.js#100]
I am trying to figure out how to free vectors. 

```
var vector = new Box2D.b2Vec2(x, y);	

var ptr1 = Box2D._malloc(0);
Box2D._free(ptr1);
Box2D._free(vector);
var ptr2 = Box2D._malloc(0);
Box2D._free(ptr2);
```

Currently when I run this, I would get memory leak eventually. Debugging shows that ptr1 and ptr2 are equal. I expect ptr2 to have -8 offset. What am I doing wrong?

**Comment by kripken** [comment]
You need to free what you malloc, but when you call `new Box2D.b2Vec2` it calls a c++ constructor, which you need to run the right destructor for. See [here](http://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/WebIDL-Binder.html#using-c-classes-in-javascript), the syntax is `Ammo.destroy(object)`.

**Comment by SneakyFernando** [comment]
@kripken, thanks for the accurate answer and provided link!
