### ISSUE TITLE
Raycast Bindings

### ISSUE THREAD

**Issue by shannon** [kripken/box2d.js#19]
I have had no luck getting RayCasting to work. There does not appear to be bindings for b2RayCastInput and b2RayCastOutput. In the ReadMe it says that you can use customizeVTable for RayCasting but without those bindings I am completely lost on how to make it work. Can someone point me in the right direction?

**Comment by otse** [comment]
Without compiling myself, how can I get basic raycasts to work?

**Comment by cwindolf** [comment]
Even when compiling yourself, do you use a JSQueryCallback to use raycasts?

**Comment by cwindolf** [comment]
Whoa, fast reply, was barely expecting one! Looks promising, thanks very much @shannon!

**Comment by IljaK** [comment]
While looking fix history and change logs, seems like b2RayCastInput/b2RayCastOutput has been already  added to b2Collision.h. But still, I'm getting exception while trying to create new instance of those objects: "cannot construct a b2RayCastInput, no constructor in IDL". Tried booth builded versions 2.3.1_min.js/2.2.1_min.js

**Comment by jobtalle** [comment]
@IljaK I'm having the same issue. I tried doing raycasts through the JSQueryCallback but they don't work for me. Any leads on how to fix this?

**Comment by jobtalle** [comment]
I did get this to work eventually. The build I'm using doesn't take `JSQueryCallback`, `b2RayCastInput` or `b2RayCastOutput`. It takes a `JSRayCastCallback` and two points. The `JSRayCastCallback` must then implement the `ReportFixture` function, which takes a fixture, a point, a normal and a fraction in that order.

**Comment by jobtalle** [comment]
Sure. In this code, `box2d` is my instantiated box2D. This code is not finished at all, but it logs the correct fraction of the ray because `ReportFixture` is called.

```    const _callback = new box2d.JSRayCastCallback();

    const configureCallback = () => {
        _callback.ReportFixture = function(fixture, point, normal, fraction) {
            const f = box2d.wrapPointer(fixture, box2d.b2Fixture);

            _callback.m_fixture = fixture;

            if (f)
                console.log(fraction);

            return fraction;
        };
    };

    /**
     * Get the length of the ray.
     * @returns {Number} The portion of the ray that could be cast in the range [0, 1].
     */
    this.getLength = () => {
        let from = body._getBody().GetWorldPoint(new box2d.b2Vec2(x, y));

        world.RayCast(
            _callback,
            new box2d.b2Vec2(from.get_x(), from.get_y()),
            new box2d.b2Vec2(from.get_x() + ray.x, from.get_y() + ray.y));

        return 0.5;
    };

    configureCallback();```
