### ISSUE TITLE
Memory won't free

### ISSUE THREAD

**Issue by SneakyFernando** [kripken/box2d.js#99]
I am trying to write a method for dynamic polygon vertices changing. And each time the method is called the dataPtr is increated by dataSize value and eventually it leads to "Box2D.js:10 Cannot enlarge memory arrays. ... " error in enlargeMemory method.

```
  SetPolygonVertices: function (polygonShape, points, offset) {
                    var n = points.length;
                    var data = null;
                    data = new Float32Array(n * 2);

                    for (var i = 0; i < n; i = (i + 1) | 0) {
                        data[Bridge.Int.mul(2, i)] = points[System.Array.index(i, points)].x + offset.x;
                        data[((1 + Bridge.Int.mul(2, i)) | 0)] = points[System.Array.index(i, points)].y + offset.y;
                    }

                    var dataSize = Bridge.Int.mul(n, 8);
                    var dataPtr = Box2D._malloc(dataSize);

                    var dataHeap = null;
                    dataHeap = new Uint8Array(Box2D.HEAPU8.buffer, dataPtr, dataSize);
                    dataHeap.set(new Uint8Array(data.buffer));
                    var dataPtrWrapped = Box2D.wrapPointer(dataPtr, Box2D.b2Vec2);
                    polygonShape.Set(dataPtrWrapped, n);
                    
                    for (var i1 = 0; i1 < n; i1 = (i1 + 1) | 0) {
                        var ptrToFree = Box2D.wrapPointer(dataPtr + Bridge.Int.mul(i1, 8), Box2D.b2Vec2);
                        Box2D._free(ptrToFree);
                    }
                },
```

**Comment by kripken** [comment]
That malloc probably should be freed - I'm not sure what the individual frees in the loop are doing, but there should just be a single free when dataPtr is no longer used.

**Comment by SneakyFernando** [comment]
In C++ free() uses actual pointer to release memory, but Box2D._malloc() returns integer value, not pointer. Should I parse it maybe?
I have divided Float32Array into n memory blocks and tried to free each in this loop by parsing integer offset with b2Vec2 size.. Is there a way to somehow free whole Float32Array?
If not, please provide me with proper examples of how should I dynamically reset vertices of polygon shape.

**Comment by SneakyFernando** [comment]
I have found that freeing by integer pointer like you have explained will actually get work done.
